#!/usr/bin/env python

from example import *
import argparse

parser = GetExampleParser(description='A program to get Palmetto examples')
parser.set_defaults(examples_dir='/software/examples/palmetto-examples')
subparsers = parser.add_subparsers()

list_subparser = subparsers.add_parser('list', help='List all available examples')
list_subparser.set_defaults(func=list_examples)

info_subparser = subparsers.add_parser('info', help='Get information about a specific example')
info_subparser.add_argument('name', help='Name of example to get info for')
info_subparser.set_defaults(func=get_example_info)

get_subparser = subparsers.add_parser('get', help='Copy example to current directory or some other specified directory')
get_subparser.add_argument('name', help='Name of example to copy')
get_subparser.add_argument('dest', nargs='?', default='', help='Destination directory')
get_subparser.set_defaults(func=get_example)

args = parser.parse_args()
args.func(args)
